# Generated by Django 3.1.5 on 2021-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_auto_20210128_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
            ],
        ),
    ]
