# Generated by Django 3.1.5 on 2021-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_blogtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtotal',
            name='extra',
            field=models.CharField(default='backend', max_length=7),
        ),
    ]
