# Generated by Django 3.1.5 on 2021-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_blogtotal_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtotal',
            name='extra',
            field=models.CharField(default='blog-total', max_length=7),
        ),
    ]
