# Generated by Django 3.1.4 on 2020-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Backend', '0001_squashed_0002_auto_20201229_1146'), ('Backend', '0002_auto_20201229_1148')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('email_url', models.EmailField(max_length=20)),
                ('extra', models.CharField(default='main', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.CharField(default='Description', max_length=50)),
                ('extra', models.CharField(default='description', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='SiteTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Title', max_length=20)),
                ('extra', models.CharField(default='title', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(default='Github Username', max_length=20)),
                ('github_tag', models.CharField(default='1.0', max_length=3)),
                ('extra', models.CharField(default='github', max_length=6)),
                ('github_repo', models.CharField(default='Github Repo Name', max_length=50)),
            ],
        ),
    ]
