# Generated by Django 3.1.4 on 2020-12-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0003_auto_20201223_1250"),
    ]

    operations = [
        migrations.RenameModel(old_name="UrlLinks", new_name="UrlLink",),
    ]
