# Generated by Django 3.1.4 on 2020-12-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0005_auto_20201224_1228"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=20)),
            ],
        ),
    ]
