# Generated by Django 3.1.4 on 2020-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0008_sitedescription_sitetitle"),
    ]

    operations = [
        migrations.DeleteModel(name="SiteName",),
        migrations.AddField(
            model_name="sitedescription",
            name="extra",
            field=models.CharField(default="-", max_length=6),
        ),
        migrations.AddField(
            model_name="sitetitle",
            name="extra",
            field=models.CharField(default="-", max_length=5),
        ),
    ]
