# Generated by Django 3.1.4 on 2020-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0009_auto_20201225_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedescription",
            name="extra",
            field=models.CharField(default="description", max_length=10),
        ),
        migrations.AlterField(
            model_name="sitetitle",
            name="extra",
            field=models.CharField(default="title", max_length=5),
        ),
    ]
