# Generated by Django 3.1.4 on 2020-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0010_auto_20201227_0045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedescription",
            name="extra",
            field=models.CharField(default="description", max_length=11),
        ),
    ]
