# Generated by Django 3.1.7 on 2021-03-09 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0002_auto_20210310_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPage',
        ),
    ]
