# Generated by Django 3.1.7 on 2021-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210310_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_title_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
