# Generated by Django 3.1.7 on 2021-03-11 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0006_auto_20210311_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogListingPage',
            new_name='BlogDetailsPage',
        ),
    ]
