# Generated by Django 3.1.7 on 2021-03-14 12:32

import blog.blocks
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogauthorsorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailspage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='blogdetailspage',
            name='page_title_description',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_title_description',
        ),
        migrations.AddField(
            model_name='blogdetailspage',
            name='blog_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogdetailspage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', blog.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
