# Generated by Django 3.1.7 on 2021-03-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210318_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetailspage',
            options={'verbose_name': 'Blog Detail', 'verbose_name_plural': 'Blog(s) Detail'},
        ),
    ]
