# Generated by Django 3.1.7 on 2021-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='main_logo',
            field=models.URLField(blank=True, help_text='Main Logo Url', null=True),
        ),
    ]
