# Generated by Django 3.1.7 on 2021-03-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('site_settings', '0002_socialmediasettings_main_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNameSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('site_description', models.CharField(max_length=100)),
                ('site_url_title', models.CharField(max_length=30)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
