# Generated by Django 3.1.4 on 2021-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20210103_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_1_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_4_url',
            field=models.URLField(default=''),
        ),
    ]
