# Generated by Django 3.1.4 on 2021-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_auto_20210103_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_1_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_4_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
