# Generated by Django 3.1.4 on 2021-01-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0005_auto_20210104_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="date_time", field=models.CharField(max_length=26),
        ),
    ]
