# Generated by Django 3.1.4 on 2021-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0009_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments", name="blog_id", field=models.IntegerField(default=0),
        ),
    ]
