# Generated by Django 3.1.5 on 2021-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_comments_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_2',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_3',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_4',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
