# Generated by Django 3.1.7 on 2021-03-18 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutusPage',
            new_name='AboutUs',
        ),
    ]
