# Generated by Django 3.1.7 on 2021-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210318_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='page_title',
            field=models.CharField(max_length=50),
        ),
    ]
